version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto20
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew bootJar
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes